version: 0.2

env:
  parameter-store:
    MPARTICLE_API_KEY: '/retaildemostore/webui/mparticle_api_key'
    MPARTICLE_SECRET_KEY: '/retaildemostore/webui/mparticle_secret_key'
    
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing NPM dependencies...
      - cd src/web-ui
      - npm ci
  build:
    commands:
      - chmod a+x *.sh
      - rm .env
      - ./gen_env.sh
      - cat .env
      - ./build.sh
  post_build:
    commands:
      - ./post_build.sh
artifacts:
  files:
    - '**/*'
  base-directory: src/web-ui/dist
