name: run-integ-tests

on:
  push: #TODO: remove this after finishing development
    branches:
      - ijemmy/integ-tests-on-aws
  workflow_dispatch: {}

env:
  STACK_NAME: retaildemostore
  STAGE_S3_BUCKET: retail-demo-store-integ-test-assets

jobs:
  testconn:
    name: Test connection
    runs-on: ubuntu-20.04
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_TO_ASSUME }}
          role-session-name: GitHub-Action-Role
          aws-region: us-west-2
      - name: Test connection
        run: |
          aws sts get-caller-identity
          echo Test using env var ${{ env.STACK_NAME }}
  stage-assets:
    name: Staging Asset
    runs-on: ubuntu-20.04
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_TO_ASSUME }}
          role-session-name: GitHub-Action-Role
          aws-region: us-west-2
      - name: Build and upload assets to an S3 bucket
        run: |
          ./stage.sh ${{ env.STAGE_S3_BUCKET }} --private-s3

  # TODO: Add following jobs in order
  # Deploy
  # Run test
  # Destroy stack